### ISSUE TITLE
安装mysql后无法退出执行下一步

### ISSUE THREAD

**Issue by ssunet** [hust-dev-summercamp/hust-summercamp-2022#12]
<img width="843" alt="截屏2022-08-16 上午10 06 11" src="https://user-images.githubusercontent.com/89333364/184783417-36eca875-dc06-4e42-acea-b12b59795ca9.png">
ctrl+c,ctrl+d,ctrl+p+q都只是打出对应文字而不退出。
重启后再输入下一步则错误
<img width="840" alt="截屏2022-08-16 上午10 07 48" src="https://user-images.githubusercontent.com/89333364/184783537-70b6b4ab-03c1-4013-9186-2c682d0509e2.png">

**Comment by y00rb** [comment]
@ssunet 第一幅图信息量太少了。你执行的命令上下文都看不到。mysql应该是正常启动了。
“重启后再输入下一步则错误”重启什么后？如果是重启容器或者系统，此时容器是退出的状态，要启动容器后才可以，执行
```bash
docker exec -it mysql-summercamp bash
```
执行如下命令，确定容器还在运行(没有退出)
```bash
docker ps
```
另外最好吧docker ps执行的结果截图贴出来。

**Comment by ssunet** [comment]
执行`docker ps`后如图，应该是运行中，但仍不能运行。
<img width="1112" alt="截屏2022-08-16 下午12 25 50" src="https://user-images.githubusercontent.com/89333364/184798806-0eb2b5f5-77d4-41af-89a3-457b9b7d7447.png">

不过删除容器再重新安装后就好了，谢谢老师。
<img width="1275" alt="截屏2022-08-16 下午12 32 01" src="https://user-images.githubusercontent.com/89333364/184799102-ad4e76fc-9423-41ca-a7b8-d682755b26b8.png">
<img width="1279" alt="截屏2022-08-16 下午12 32 33" src="https://user-images.githubusercontent.com/89333364/184799134-af5cc240-ee72-42d1-a801-24d20fb8400e.png">

<img width="1126" alt="截屏2022-08-16 下午12 39 08" src="https://user-images.githubusercontent.com/89333364/184799066-adea7787-a79e-4688-8011-d5c10c47eedb.png">
