### ISSUE TITLE
phase2安装node时出现问题

### ISSUE THREAD

**Issue by ssunet** [hust-dev-summercamp/hust-summercamp-2022#15]
执行`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash`后
<img width="813" alt="截屏2022-08-16 下午1 06 38" src="https://user-images.githubusercontent.com/89333364/184802509-f1c9dd66-bcfb-4b3f-b484-ffe1d38a0f57.png">
再执行`nvm install 16.13`f发生错误
<img width="520" alt="截屏2022-08-16 下午1 06 51" src="https://user-images.githubusercontent.com/89333364/184802590-9f740b79-476f-4beb-9051-cf09a4f4532e.png">
网上查找之后在两句之间加上了`source ~/.bashrc`成功进行了
<img width="664" alt="截屏2022-08-16 下午1 07 05" src="https://user-images.githubusercontent.com/89333364/184802779-b88f1c0c-4013-4b03-9b11-9712f72ba4ff.png">
不知道对不对

**Comment by y00rb** [comment]
@ssunet  对的 👍。部分安装需要source一下`.bashrc`文件。

**Comment by y00rb** [comment]
https://github.com/hust-dev-summercamp/hust-summercamp-2022/issues/9
这两个问题类似的。
