### ISSUE TITLE
phase3时host一直not yet available

### ISSUE THREAD

**Issue by ssunet** [hust-dev-summercamp/hust-summercamp-2022#16]
执行`docker-compose up --build`后，redis6379接口一直连接不上
<img width="1288" alt="截屏2022-08-16 下午2 34 30" src="https://user-images.githubusercontent.com/89333364/184816776-5d4951ca-aacd-45ec-94c4-be0816209854.png">
看到其中有一句

> redis_1          | 1:M 16 Aug 2022 06:56:05.303 # Can't open the append-only file: Permission denied

或许是这个的问题

试着开启iptables但无用
<img width="762" alt="截屏2022-08-16 下午2 50 29" src="https://user-images.githubusercontent.com/89333364/184816982-b7e2bbf1-f8a7-4539-9c04-b0dc872f362a.png">

**Comment by y00rb** [comment]
@ssunet 感觉要么是port的问题，要么是volume的问题。有修改docker-compose.yml文件吗？

**Comment by y00rb** [comment]
@ssunet 首先查看 /tmp/redis-data 这个目录是否存在。如果存在，试试如下命令
```bash
sudo chown 1001 /tmp/redis-data
```
然后再重新运行命令启动容器
```bash
docker-compose up --build
```
我是这里看到的，试试
https://hub.docker.com/r/bitnami/redis
<img width="855" alt="image" src="https://user-images.githubusercontent.com/444876/184824978-0e87d843-4483-4d89-a30b-2014fa1c1fa9.png">

**Comment by ssunet** [comment]
存在 /tmp/redis-data ，用了`sudo chown 1001 /tmp/redis-data`之后就成功了，谢谢老师。

现在网页显示这样：
<img width="1440" alt="截屏2022-08-16 下午3 53 43" src="https://user-images.githubusercontent.com/89333364/184827475-fa7dbf3c-5ecb-4762-b0fb-6dcb4add0a14.png">
服务器是这样：
<img width="841" alt="截屏2022-08-16 下午3 51 22" src="https://user-images.githubusercontent.com/89333364/184827544-2cb3dc8b-f5b6-41b4-9da8-b1163d541a5a.png">
请问网址应该是什么呢

**Comment by y00rb** [comment]
@ssunet 应该是http://localhost:8181/ 
你可以看看 docker的文档，
<img width="545" alt="image" src="https://user-images.githubusercontent.com/444876/184848668-76eba511-a52f-496e-a5ca-f657ec00c64c.png">

容器内，我启动了一个nginx，然后nginx开发80端口（容器内），我使用本机（local）的8181端口与容器的80做映射。这样访问8181就会被transfer到容器的80。

**Comment by y00rb** [comment]
你访问的8080是api的路由

**Comment by ssunet** [comment]
进入网页了，但登陆又出问题了。
<img width="839" alt="截屏2022-08-16 下午8 53 37" src="https://user-images.githubusercontent.com/89333364/184885255-c2acc965-e16d-43c8-8596-cdd895b29295.png">
看上去应该是这一步出错
<img width="753" alt="截屏2022-08-16 下午8 53 52" src="https://user-images.githubusercontent.com/89333364/184885355-44ffb2e5-bdf9-4aa5-9a20-61900f72076d.png">

**Comment by y00rb** [comment]
```bash
docker ps
```
会看到这些内容：
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/444876/185746719-64d5396c-62c9-4327-ae98-bd47504fa576.png">
然后执行命令
```bash
docker exec -it phase3_db_1 bash
```
会进入mysql的容器
<img width="733" alt="image" src="https://user-images.githubusercontent.com/444876/185746743-657c0faf-a6b9-4077-aebc-0d2813aae008.png">
然后执行文档阶段一中的步骤：
https://github.com/hust-dev-summercamp/hust-summercamp-2022#%E9%98%B6%E6%AE%B51
<img width="722" alt="image" src="https://user-images.githubusercontent.com/444876/185746816-423ca2f6-f6c4-4177-b48d-c405b44ccf2f.png">
