### ISSUE TITLE
用virtualbox安装Ubuntu，更改虚拟机配置的更改存储选项的一步，选择虚拟盘之后没有对应的光盘印象

### ISSUE THREAD

**Issue by Alex-Authur** [hust-dev-summercamp/hust-summercamp-2022#5]

**Comment by y00rb** [comment]
同学，你好，不太清楚你遇到的具体问题是什么。是不是你更改错了什么配置？如果方便截图一下？安装虚拟机的步骤网上很多教程了，可以按照教程一步步执行。如果是更改存储大小。不会影响虚拟机的安装的。

**Comment by Alex-Authur** [comment]
![Uploading image.png…]()

**Comment by Alex-Authur** [comment]
> 成员
是没有盘片
![image](https://user-images.githubusercontent.com/111232559/184539452-19d3464a-4623-4533-bc81-e3b72203c20a.png)
